Fine-tuned the style of contribution grid, which is exactly the same as github
sallar/github-contributions-canvas pull request #27
Opened 2020-10-12 10:23 UTC by xiandanin

Added __rounded corners__, __border__, __corrected colors__, and the parameters are completely referenced to the latest github, making it closer to the style of github.

![image](https://user-images.githubusercontent.com/17588779/95735488-736cf100-0cb7-11eb-822b-7f131ea3dc86.png)

2020-10-12 14:20 UTC, sallar requested changes
Thanks for your PR. This is a great idea. However there are a few things that need to be fixed that I have commented on the PR.

But also, I think this needs to be a "theme option", for example the classic github theme didnt have rounded corners, etc. Or maybe an option on the whole package, that the user can control.

2020-10-12 14:20 UTC, sallar commented on __tests__/draw.test.js
> +  /*
this comment can be removed

2020-10-12 14:20 UTC, sallar commented on __tests__/draw.test.js
> +import fs from "fs";
unnecessary import

2020-10-12 14:20 UTC, sallar commented on __tests__/draw.test.js
> +    scaleFactor: 2
this should be dynamic

2020-10-12 14:20 UTC, sallar commented on src/themes.js
> +    meta: "#767676",
the test text colors were white before the text rendering isn't the same on the CI vs the dev machine, so they need to be white so the tests wont fail

2020-10-12 14:20 UTC, sallar commented on src/themes.js
> +    stroke:'rgba(27,31,35,.04)',
the other themes dont have strokes... what happens?

2020-10-12 14:20 UTC, sallar commented on src/index.js
> +      ctx.strokeStyle = theme["stroke"];
Since the other themes dont have strokes this fails

2020-10-12 14:20 UTC, sallar commented on src/index.js
> +    ctx.strokeStyle = theme["stroke"];
also this

2020-10-12 15:39 UTC, xiandanin commented
> Thanks for your PR. This is a great idea. However there are a few things that need to be fixed that I have commented on the PR.
> 
> But also, I think this needs to be a "theme option", for example the classic github theme didnt have rounded corners, etc. Or maybe an option on the whole package, that the user can control.

I made some modifications as you suggested:
* I added the "newGithub" theme to show that this is the latest official github style.
* Added "radius" and "stroke" parameters, but this is optional. If the theme does not contain this parameter, it will work normally.
* Change the text color of "__test__" theme to white.
* "scaleFactor" can still be passed in as a parameter, but it is dynamic by default.

2020-10-15 10:12 UTC, xiandanin reviewed
> Thanks for your PR. This is a great idea. However there are a few things that need to be fixed that I have commented on the PR.
> 
> But also, I think this needs to be a "theme option", for example the classic github theme didnt have rounded corners, etc. Or maybe an option on the whole package, that the user can control.

I made some modifications as you suggested:
* I added the "newGithub" theme to show that this is the latest official github style.
* Added "radius" and "stroke" parameters, but this is optional. If the theme does not contain this parameter, it will work normally.
* Change the text color of "__test__" theme to white.
* "scaleFactor" can still be passed in as a parameter, but it is dynamic by default.

2021-01-18 08:06 UTC, sallar commented
I apologize for not merging this yet @xiandanin - I need to get a chance to sit down and work on this.

2023-02-09 12:09 UTC, closed without merging