Solarized themes
sallar/github-contributions-canvas pull request #35
Opened 2021-03-04 23:41 UTC by solean

Added Solarized themes :)

<img width="1283" alt="Screen Shot 2021-03-04 at 6 02 30 PM" src="https://user-images.githubusercontent.com/4016993/110045762-2ac2dc80-7d19-11eb-9c7a-0184b052e464.png">

<img width="1259" alt="Screen Shot 2021-03-04 at 6 02 36 PM" src="https://user-images.githubusercontent.com/4016993/110045760-2991af80-7d19-11eb-8c10-975e7122b998.png">

2021-03-05 09:44 UTC, sallar requested changes
Thank you! this is great. just one small change needed

2021-03-05 09:44 UTC, sallar commented on README.md
> +- `Solarized Dark`
these need to be the keys not the names

2021-03-11 23:02 UTC, solean commented on README.md
> +- `Solarized Dark`
Oops, changing that now 😅

2021-03-12 12:09 UTC, sallar approved these changes

2021-03-12 12:09 UTC, merged